version: '3'
services:
  db:
    container_name: admin_panel_db
    restart: always
    image: postgres:14.3
    environment:
      POSTGRES_DB: movies_database
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123qwe
    env_file:
      - ./envs/.env
    volumes:
      - ./admin_panel/app/db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data/
    expose:
      - 5432

  app:
    container_name: admin_panel_app
    restart: always
    build:
        context: .
        dockerfile: ./docker/Dockerfile.admin_panel
    env_file: ./envs/.env
    volumes:
      - ./logs:/app/logs
      - static:/app/data/static
      - media:/app/data/media
    entrypoint: ["sh", "run.sh"]
    depends_on:
      - db
    expose:
      - 8000
  
  fastapi:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.async_api
      args:
        PROJECT_ENV: production
    env_file:
      - ./envs/.env
    depends_on:
      - db
      - elasticsearch
      - redis
    expose:
      - 8000
    restart: always

  nginx:
    container_name: admin_panel_nginx
    restart: always
    image: nginx:1.23.0
    volumes:
      - static:/data/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - app
      - db
    ports:
      - 80:80

  redis:
    container_name: admin_panel_redis
    restart: always
    image: redis:7.0.4
    expose:
      - 6379
    volumes:
      - cache:/data
  
  etl:
    container_name: admin_panel_etl
    restart: always
    build:
        context: .
        dockerfile: ./docker/Dockerfile.etl
    env_file: ./envs/.env
    volumes:
      - ./async_api/etl/logs:/etl/logs
      - ./async_api/etl/data:/etl/data
    entrypoint: ["sh", "run.sh"]
    depends_on:
      - app
      - db
      - elasticsearch

  elasticsearch:
    container_name: admin_panel_elastic
    restart: always
    image: elasticsearch:7.17.5
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  static:
  media:
  db_data:
  cache:
  es_data:
